[package]
name = "proxmox"
version = "0.1.0"
authors = ["Andor Uhlár <andor44@gmail.com>"]

[dependencies]
log = "0.4"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

reqwest = "0.9"
url = "1.7"

[dev-dependencies]
pretty_env_logger = "*"
